Remove OpenRC code from pe-format2-setup.

diff --git a/pe-format2-setup.in b/pe-format2-setup.in
--- a/pe-format2-setup.in
+++ b/pe-format2-setup.in
@@ -1,14 +1,5 @@
 #!/bin/sh
-# Regenerate the configuration for pe-exec, using the variables exported
-# in the environment (hopefully by the init.d script).
-
-if [ -n "${RC_SVCNAME}" ]; then
-	ewarn=ewarn
-	eerror=eerror
-else
-	ewarn=echo
-	eerror=echo
-fi
+# Regenerate the configuration for pe-exec.
 
 firstworking() {
 	while [ ${#} -gt 1 ]; do
@@ -19,7 +10,7 @@ firstworking() {
 		shift
 	done
 
-	${ewarn} "\${${1}} is not set and none of the default applications were found!" >&2
+	echo "\${${1}} is not set and none of the default applications were found!" >&2
 }
 
 : ${UNKNOWN:=$(firstworking wine mono ilrun dosbox dosemu UNKNOWN)}
@@ -29,7 +20,7 @@ firstworking() {
 : ${WIN64:=$(firstworking wine64 WIN64)}
 
 if [ -z "${UNKNOWN}" -a -z "${MSDOS}" -a -z "${WIN32}" -a -z "${CLR}" -a -z "${WIN64}" ]; then
-	${eerror} 'None of the expected interpreters were set, aborting.' >&2
+	echo 'None of the expected interpreters were set, aborting.' >&2
 	exit 1
 else
 	printf '%s\0' "${UNKNOWN}" "${MSDOS}" "${WIN32}" "${CLR}" "${WIN64}" > @pkgstatefile@
